config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: %i[index create]
  
  resources :songs
  root 'songs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    respond_to do |format|
      if !params[:buscador].nil?
        if params[:buscador].blank?
          @comments = Comment.all
        else
          @comments = Comment.where('content LIKE ?', "%#{params[:buscador]}%")
        end
        format.js
      else
        @comments = Comment.all
        format.html
      end
    end
  end

  def create
    @comment = Comment.new(content: params[:comment][:content])
    @comment.save
    respond_to { |format| format.js }
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def add_content
    @title = params[:title]
    respond_to do |format|
      format.js
    end
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
    @song = Song.new
    respond_to do |format|
      format.html
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    respond_to :js
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
    respond_to :js
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.js
      else
        format.html { redirect_to songs_path, alert: 'Error. Intente nuevamente' }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.js
      else
        format.html { redirect_to songs_path, alert: "Error al actualizar: #{@song.errors.messages}"}
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to :js
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/comments/_comment.html.erb
<li><%= comment.content %></li>

app/views/comments/create.js.erb
$('#lista').prepend("<li><%= @comment.content %></li>");
$("[name='comment[content]']").val('');

app/views/comments/index.html.erb
<h1>
  Bienvenido a mi landing!
</h1>


<%= form_with(model: Comment.new, local: true) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit :enviar %>
<% end %>

<br><br>
<label for="">Buscar:</label>
<input type="text" id="buscador">


<ul id="lista">
  <%= render @comments %>
</ul>

<iframe width="300" height="200" src="https://www.youtube.com/embed/bOsKJpCR9Fo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<br>
<br>

<script>
  $('#buscador').keyup(function () {
    var searchQuery = $('#buscador').val();
    $.ajax({
      type: "GET",
      url: "<%= comments_path %>",
      data: { buscador: searchQuery }
    });
  });
</script>

<script>
  $("[name='commit']").click(function(event) {
    event.preventDefault();
    var commentContent = $("[name='comment[content]']").val();
    $.ajax({
      type: "POST",
      url: "<%= comments_path %>",
      data: { comment: { content: commentContent } }
    });
  })
</script>

app/views/comments/index.js.erb
$('#lista').html("<%= j render @comments %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h5 style="text-align:center; color: gray;">[imagina un navbar aquí]</h5>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<%= link_to 'HOME', pages_home_path %>

app/views/pages/add_content.js.erb
$('#lista').append('<li><%= @title %></li>');

app/views/pages/home.html.erb
<h1 id="titulo">
  Estamos en el HOME!
</h1>

<iframe width="300" height="200" src="https://www.youtube.com/embed/bOsKJpCR9Fo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<br>
<input type="text" id="title">
<button onclick="realizarLlamada()">Agregar</button>

<ol id="lista">
</ol>

<script>
  function realizarLlamada() {
    var contenidoDelInput = $('#title').val();
    $.ajax({
      type: "POST",
      url: "<%= pages_add_content_path %>",
      data: {title: contenidoDelInput}
    })
    .fail(function() { alert('FALLAAAA!') })
  };
</script>

app/views/songs/_edit_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
      </div>
    </div>
  </div>
</div>

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/_show.html.erb
<p>
  <strong>Title:</strong>
  <%= song.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= song.artist %>
</p>

app/views/songs/_song.html.erb
<tr id="<%= song.id %>">
  <td><%= song.title %></td>
  <td><%= song.artist %></td>
  <td><%= link_to 'Show', song, data: {remote: true} %></td>
  <td><%= link_to 'Edit', edit_song_path(song), data:{remote: true} %></td>
  <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?', remote: true } %></td>
</tr>

<script>
  {/* $('#show').click(function() {
    $.ajax({
    type: "GET",
    url: "<%= song_path(song.id) %>",
    data: {id: song.id},
    success: function (response) {
      
    }
  });
  }) */}
</script>

app/views/songs/create.js.erb
$('tbody').append("<%= j render @song %>");
$('#song_title').val('');
$("[name='song[artist]']").val('');

app/views/songs/destroy.js.erb
$("#<%= @song.id %>").toggle(1000);

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/edit.js.erb
$('.modal-body').html("<%= j render 'form', song: @song %>");
$('#exampleModal').modal('show');

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Songs</h1>

<%= render 'form', song: @song %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @songs %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

<!-- Modal -->
<%= render 'edit_modal' %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.js.erb
$('.modal-body').html("<%= j render 'songs/show', song: @song %>");
$('#exampleModal').modal('show');

app/views/songs/update.js.erb
// Actualizar el registro en la tabla.
$("#<%= @song.id %>").replaceWith("<%= j render @song %>");

// Esconder el modal.
$('#exampleModal').modal('hide');